### ISSUE TITLE
Lander in HD landing exactly in where the cursor is

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod-Archived#13]
There is suppose to be a randomization so the player doesn't land exactly on target, pickup what they want, and take off thereby avoiding obstacles.   This seems to be working properly in the original graphics setting.    I think this is new to Rev 8

**Comment by Serosis** [comment]
That was part of the "GodMode always on" bug and has been fixed now in the latest release.
