### ISSUE TITLE
Cannot leave planet issue

### ISSUE THREAD

**Issue by Br3ach** [JHGuitarFreak/UQM-MegaMod-Archived#14]
v0.8.0.81 MegaMod, Windows

Check the attached save game. For some reason leaving orbit immediately returns me to the planet. Happened only once so far. I suppose this has to do with the 'enter orbit on touching planet edge' change (?). Workaround: use auto-pilot to get out.

[uqmsave.zip](https://github.com/Serosis/UQM-MegaMod/files/2439907/uqmsave.zip)

**Comment by Serosis** [comment]
I didn't seem to have any issue leaving the moon you were in orbit of or its parent planet in your saved game. 

Is it a certain direction you were leaving per chance?

**Comment by Br3ach** [comment]
> I didn't seem to have any issue leaving the moon you were in orbit of or its parent planet in your saved game.
> 
> Is it a certain direction you were leaving per chance?

No, I don't think it's direction-related. So far it happened maybe 5 times out of 200 or so, I can't really find a rule... 

It's strange that you can't reproduce with my save - perhaps it's resolution-related...? I'm playing at 1280x960.

Here's a video: https://www.dropbox.com/s/jg8zjsro1wa6787/UrQuanMasters%202018-10-07%2012-10-56-38.avi?dl=0

**Comment by Serosis** [comment]
Oh, ok, I see what's going on. You had orbiting planets enabled and that allowed one of the moons to get super close to the gas giant.

I'll nerf the intersect point to be "under the skin" on HD for the next release. Try to get a happy medium between the original pixel point in the center and the outer skin of the planet.
