### ISSUE TITLE
HD Cutscene slides black when Volasaurus or Precursor Music are selected 0.8.0.83

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod-Archived#18]
Didn't notice this till now.  Was the same on my linux box and a windows machine.

**Comment by Serosis** [comment]
Yet another oversight on my part. I guess 0.8.0.85 is coming up next...

Actually, this is a content issue. I forgot to update Vol's package and the Remix timing package.

**Comment by Serosis** [comment]
Fixed, redownload Volasaurus' remix package and/or the Precursor's remix timing file for MegaMod:

http://files.serosis.net/MegaMod/volasaurus-remix-pack.uqm

http://files.serosis.net/MegaMod/mm-remix-timing.uqm

**Comment by JoshuaPettus** [comment]
Excellent!  So glad you didn't have to do another re-release.  I felt so bad when you put in .84 and I only just put this ticket in.
