### ISSUE TITLE
Change build LINK name

### ISSUE THREAD

**Issue by iuriguilherme** [JHGuitarFreak/UQM-MegaMod-Archived#2]
Installing on Linux would overwrite vanilla `uqm` and/or `uqm-hd` located at `/usr/local/games/`.

Just like HD mod does, the binary produced through building should default to something like `uqm-mm` and `uqm-mm-hd` (or `uqm-hd-mm`).

**Comment by Serosis** [comment]
Tell me how you got it built in Linux and I'll plug the changes in myself. But as a point of reference I always meant for my mod to be slotted over vanilla Classic and HD.

I guess with the most recent changes it wouldn't be as simple as that.

**Comment by iuriguilherme** [comment]
I appreciate the effort you made into making the modifications non intrusive and optional, but still my opinion would be to not overwrite the vanilla game by default.

Unless it were a simple matter of adding `.uqm` files in the addon folder.

I built using the regular methods, I can't recall it right now, but I'll read my shell history so I can write a step by step. I built in a fedora system but I'll build in debian too, so I can document which packages shall be installed.

**Comment by Serosis** [comment]
The mod's original intent was to sit next to or overwrite the vanilla executable as a way to help out a tough situation, depending on the situation you were in.

There were three different executables at one point for the Time Dilation, Kohr-Stahp, and FMV portions of this mod. Back when I knew nothing about how UQM worked internally.

To give you an idea on how far back this goes: 
2005-2007: https://web-beta.archive.org/web/20070317023306/http://www.dickweed.0nyx.com:80/downloads.htm (This one forces your browser to download an MP3 of the Kohr-Ah theme, no idea why.)
2007-2009: https://web.archive.org/web/20070121160340/http://uqm-mods.sourceforge.net
2009-2012: http://uqm-mods.sourceforge.net/Classic
2012-2013: http://uqm-mods.sourceforge.net/OldSWF

**Comment by Serosis** [comment]
I'm going to close this for now since it isn't a game-breaking bug. But I will reopen it when I am able to actually build and install it on modern Linux.

I just do not have the patience, at the moment, to figure out why it goes wrong on my end.

**Comment by Serosis** [comment]
An update to this issue.

When the 0.8.0-HD version is completed it will have it's own settings directory (LINK name).

It will also be the sole version available on this Git.
