### ISSUE TITLE
Shofixti glory device damage should not be scaled with resolution

### ISSUE THREAD

**Issue by Ala-lala** [JHGuitarFreak/UQM-MegaMod-Archived#20]
Currently, it's scaled *twice*: once since the max damage calculation uses the max range, which is already scaled, and twice because it scales that range *again*; I'm guessing that second scale was meant to be a descale.

**Comment by Serosis** [comment]
Already killing it with the bug reports. Thanks again!

**Comment by Serosis** [comment]
Took a look and you're right but _DESTRUCT_RANGE_ definitely needs to be scaled. Removed the superfluous RES_SCALE from _MAX_DESTRUCTION_ though.

**Comment by Serosis** [comment]
I'm going to do some preliminary testing (probably should have done that before I pushed the fix) by testing distance to damage in SD and HD to see if they match up consistently.

**Comment by Serosis** [comment]
Alrighty, I fixed it by separating DESTRUCT_RANGE from MAX_DESTRUCTION.

MAX_DESTRUCTION is *always* supposed to be (180 / 10) whereas DESTRUCT_RANGE also needs to be RES_SCALE'd.
