### ISSUE TITLE
PANIC: Sero Setup not found in addons directory!

### ISSUE THREAD

**Issue by iuriguilherme** [JHGuitarFreak/UQM-MegaMod-Archived#3]
Where should those files come from?

```
Warning: Addon 'rmx-subtitle' not found
Warning: Addon 'rmx-shofixti' not found
Warning: Addon 'rmx-utwig' not found
Warning: Addon 'MelnormeVoicePack' not found
Warning: Addon 'MyconVoiceFix' not found
Warning: Addon 'sero-menu-1x' not found
Warning: Addon 'sero-setup-classic' not found

PANIC: Sero Setup not found in addons directory!
```

**Comment by iuriguilherme** [comment]
It's all on sourceforge, files list here: <http://uqm-mods.sourceforge.net/Releases> ou here: <https://serosis.github.io/#Releases>

**Comment by iuriguilherme** [comment]
Reopening because this should be in the building docs along with the vanilla content instruction

**Comment by Serosis** [comment]
Only the Sero Setup is necessary. Those other files are checked on each load, if they are found they are loaded, if not, warning.

It's a bit verbose but it does its job.

I'll add the info to the README.md and the build docs when I get the chance.

UPDATE:

Added content info and links to the README.md along with the INSTALL and README for the projects as well.
