### ISSUE TITLE
MelnormeVoicePack does not autoload

### ISSUE THREAD

**Issue by clst** [JHGuitarFreak/UQM-MegaMod-Archived#4]
Hi,
great work compiling all this stuff. Sadly Version 1.1 of MelnormeVoicePack doesn't autoload:
```Warning: Addon 'MelnormeVoicePack' not found```

This is not the right path for the ZIP file from: http://www.warpstormstudios.com/uqmmod/
The folder for the fix is: ```MelnormeVoiceFix```
You can rename the folder in the ZIP or change ```setup.c``` to fix.

If the change was done in 1.1 maybe Soul Reaver didn't know he broke your autoloader. ;)

**Comment by Serosis** [comment]
Yes, thank you for finding this. It seems SoulReaver changed the name so it indeed broke the autoloader for both 0.8.0 *and* HD.

Fun stuff. If you're on Windows you can grab a new EXE in the bin folder.

I'll update the main release files today if I can make the new binaries before dinner.

UPDATE:

Main 0.8.0 release files updated
