### ISSUE TITLE
hayes dialogue 

### ISSUE THREAD

**Issue by TornadoKirby** [JHGuitarFreak/UQM-MegaMod-Archived#5]
in 0.8.0, commander hayes dialogue is very, very bizarre after the game opens up (after you fight the ilwrath ship, the time skip, etc.) 
the dialogue options generally seem to do what they're supposed to, but the text lines (and their respective voiced lines - i've tried it with speech both off and on) seem to be quite jumbled around.

**Comment by Serosis** [comment]
Which 0.8.0, plain or HD?

I've played through it myself and never noticed anything odd.

Could you get a screen record or screenshots?

EDIT:

Check to make sure your content doesn't include anything from 0.7.0, this includes the base content and voices.

The only 0.7.0 contents that are supported are the 3DO music and videos along with the Precursor remixes.

0.8.0 has its own version of the base content and voices that you can download here: http://uqm-mods.sourceforge.net/Releases

**Comment by TornadoKirby** [comment]
this would be the plain, non-HD 0.8.0 beta, the most recent release.

here's what my /content/addons/ folder looks like:
https://i.imgur.com/pmBlPjG.png
and the /content/packages/ folder only has uqm-0.8.0-content.uqm inside.

here's a video of my very interesting conversation with commander hayes, fresh from the starting sequence of the game. (granted, with the head start cheat used as well.)
https://www.youtube.com/watch?v=8GIo8CfeeO0

**Comment by Serosis** [comment]
I can not repeat this at all on my end.

Try removing RMX subtitle and/or 3DO voice. Those are the only two files in your addons that would interfere with subtitles and responses.

I can only think that one or the other may be corrupted or both in tandem screw everything up. In which case I need to update the site to reflect as such.

**Comment by TornadoKirby** [comment]
alright, i've tested it three times:
- with both rmx-subtitle and uqm-0.8.0-3dovoice, which made it screw up
- with uqm-0.8.0-3dovoice removed, which made it work fine (but obviously without voices)
- with rmx-subtitle removed, which made it work just fine overall

looks like as you suggested, having them both in tandem screws everything up, for some reason
very curious

**Comment by Serosis** [comment]
Cool, thanks for testing. I'll update the website to reflect that rmx-subtitle should only be used with 0.7.0.
