### ISSUE TITLE
Timing in the utwig remix voice package may need to be adjusted for 0.8.0

### ISSUE THREAD

**Issue by JoshuaPettus** [JHGuitarFreak/UQM-MegaMod-Archived#8]
This happened to me in Rev.6 on the windows release, though something tells me it's not platform specific.  I'll see if I can put up some specifics.

[EDIT]
After the first introduction, it seems like every dialog option is off...

**Comment by Serosis** [comment]
Must have been that way for awhile. I'll take a look but I don't know the timing files very well.

**Comment by JoshuaPettus** [comment]
Maybe soulreaver would be willing to takeca look at it?

**Comment by Serosis** [comment]
Fixed.

**Comment by JoshuaPettus** [comment]
Totally awesome!  I will give this a try as soon as I get some free time!  Can't stand the original 3do voice XD.  Has there been an update to the utwig voice pack?  Or is this entirely code?

**Comment by Serosis** [comment]
It was an update to the voice pack.

What happened was an oversight on my end. I lifted the voice pack from HD-Remix's files but mistakenly applied the original 3DO voice timing file.

This has been rectified by porting HD-Remix's timing file and subtitles to the 0.8.0 platform.
