### ISSUE TITLE
Crash on dialogue

### ISSUE THREAD

**Issue by gunnar123abc** [JHGuitarFreak/UQM-MegaMod-Archived#9]
When speaking to the malfunctioning zapping robots, at some point is allowed to pose a question to them, something along the lines of... "you know. . . right?" and then they state some co-ordinates (presumably to their homeworld). It crashes on this dialogue of the coordinates. 625.8 181.6

I am using windows 7, with the mega mod installed, along with the optional voice packs, having voices from 3DO labeled on.

It has happened two times in a row, so for now on I will avoid asking the question to them.

**Comment by Serosis** [comment]
Thanks for letting me know, sorry it took so long to respond i will look into it tomorrow.

**Comment by Serosis** [comment]
Alrighty, I ran into your bug and it's a doozy. I'm at work fixing it right now.

**Comment by Serosis** [comment]
Looks like it was a corrupted audio file, all fixed now: https://streamable.com/kcufa

I'll be releasing Revision 8 either tomorrow or Friday so you'll be able to pick up the updated files then.
